// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wihngo.Data;

#nullable disable

namespace Wihngo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251208145119_AddLoveCompositeKey")]
    partial class AddLoveCompositeKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.Property<Guid>("BirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<int>("LovedCount")
                        .HasColumnType("integer")
                        .HasColumnName("loved_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Species")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("species");

                    b.Property<int>("SupportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("supported_count");

                    b.Property<string>("Tagline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tagline");

                    b.HasKey("BirdId");

                    b.HasIndex("OwnerId");

                    b.ToTable("birds", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Love", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "BirdId");

                    b.HasIndex("BirdId");

                    b.ToTable("loves", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Story", b =>
                {
                    b.Property<Guid>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.HasKey("StoryId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BirdId");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.SupportTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("SupporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("supporter_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("BirdId");

                    b.HasIndex("SupporterId");

                    b.ToTable("support_transactions", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.SupportUsage", b =>
                {
                    b.Property<Guid>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usage_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.HasKey("UsageId");

                    b.HasIndex("BirdId");

                    b.HasIndex("ReportedBy");

                    b.ToTable("support_usage", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("profile_image");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.HasOne("Wihngo.Models.User", "Owner")
                        .WithMany("Birds")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Wihngo.Models.Love", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("Loves")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "User")
                        .WithMany("Loves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wihngo.Models.Story", b =>
                {
                    b.HasOne("Wihngo.Models.User", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("Stories")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("Wihngo.Models.SupportTransaction", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("SupportTransactions")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "Supporter")
                        .WithMany("SupportTransactions")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Wihngo.Models.SupportUsage", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("SupportUsages")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "Reporter")
                        .WithMany("ReportedSupportUsage")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.Navigation("Loves");

                    b.Navigation("Stories");

                    b.Navigation("SupportTransactions");

                    b.Navigation("SupportUsages");
                });

            modelBuilder.Entity("Wihngo.Models.User", b =>
                {
                    b.Navigation("Birds");

                    b.Navigation("Loves");

                    b.Navigation("ReportedSupportUsage");

                    b.Navigation("Stories");

                    b.Navigation("SupportTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
