// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wihngo.Data;

#nullable disable

namespace Wihngo.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210005314_AddBirdPremiumColumns")]
    partial class AddBirdPremiumColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.Property<Guid>("BirdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<long>("DonationCents")
                        .HasColumnType("bigint")
                        .HasColumnName("donation_cents");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.Property<int>("LovedCount")
                        .HasColumnType("integer")
                        .HasColumnName("loved_count");

                    b.Property<int>("MaxMediaCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_media_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PremiumExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("premium_expires_at");

                    b.Property<string>("PremiumPlan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("premium_plan");

                    b.Property<string>("PremiumStyleJson")
                        .HasColumnType("text")
                        .HasColumnName("premium_style_json");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("qr_code_url");

                    b.Property<string>("Species")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("species");

                    b.Property<int>("SupportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("supported_count");

                    b.Property<string>("Tagline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tagline");

                    b.HasKey("BirdId");

                    b.HasIndex("OwnerId");

                    b.ToTable("birds", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.BirdPremiumSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceled_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan");

                    b.Property<long>("PriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_cents");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BirdId");

                    b.HasIndex("OwnerId");

                    b.ToTable("bird_premium_subscriptions", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Entities.CryptoExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<decimal>("UsdRate")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("usd_rate");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .IsUnique();

                    b.ToTable("crypto_exchange_rates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("269e39df-8fc8-4b37-9b37-5ee3491ea04e"),
                            Currency = "BTC",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2547),
                            Source = "coingecko",
                            UsdRate = 50000m
                        },
                        new
                        {
                            Id = new Guid("92860bc0-7342-4749-ac2d-0727f0264b4e"),
                            Currency = "ETH",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2553),
                            Source = "coingecko",
                            UsdRate = 3000m
                        },
                        new
                        {
                            Id = new Guid("7df322cb-48c3-445f-8380-5c52ee6a0ec4"),
                            Currency = "USDT",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2555),
                            Source = "coingecko",
                            UsdRate = 1m
                        },
                        new
                        {
                            Id = new Guid("26106c54-99bb-4f9a-81f5-9845a95a05ec"),
                            Currency = "USDC",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2568),
                            Source = "coingecko",
                            UsdRate = 1m
                        },
                        new
                        {
                            Id = new Guid("b3ab45ce-c2ee-4a74-8feb-70ee37d86071"),
                            Currency = "BNB",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2570),
                            Source = "coingecko",
                            UsdRate = 500m
                        },
                        new
                        {
                            Id = new Guid("3b8b5ffc-8dde-4a0f-b2d9-f9f356c528ee"),
                            Currency = "SOL",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2573),
                            Source = "coingecko",
                            UsdRate = 100m
                        },
                        new
                        {
                            Id = new Guid("2ab74aaa-79b0-48ac-b463-1c31631f8ff9"),
                            Currency = "DOGE",
                            LastUpdated = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2575),
                            Source = "coingecko",
                            UsdRate = 0.1m
                        });
                });

            modelBuilder.Entity("Wihngo.Models.Entities.CryptoPaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WalletAddress", "Currency", "Network")
                        .IsUnique();

                    b.ToTable("crypto_payment_methods");
                });

            modelBuilder.Entity("Wihngo.Models.Entities.CryptoPaymentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountCrypto")
                        .HasColumnType("decimal(20,10)")
                        .HasColumnName("amount_crypto");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount_usd");

                    b.Property<Guid?>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer")
                        .HasColumnName("confirmations");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(20,2)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network");

                    b.Property<string>("PaymentUri")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_uri");

                    b.Property<string>("Plan")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("purpose");

                    b.Property<string>("QrCodeData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_code_data");

                    b.Property<int>("RequiredConfirmations")
                        .HasColumnType("integer")
                        .HasColumnName("required_confirmations");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TransactionHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transaction_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserWalletAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_wallet_address");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("wallet_address");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("TransactionHash");

                    b.ToTable("crypto_payment_requests");
                });

            modelBuilder.Entity("Wihngo.Models.Entities.CryptoTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(20,10)")
                        .HasColumnName("amount");

                    b.Property<string>("BlockHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("block_hash");

                    b.Property<long?>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer")
                        .HasColumnName("confirmations");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(20,10)")
                        .HasColumnName("fee");

                    b.Property<string>("FromAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("from_address");

                    b.Property<long?>("GasUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("gas_used");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network");

                    b.Property<Guid>("PaymentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_request_id");

                    b.Property<string>("RawTransaction")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_transaction");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("to_address");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("transaction_hash");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId");

                    b.HasIndex("TransactionHash")
                        .IsUnique();

                    b.ToTable("crypto_transactions");
                });

            modelBuilder.Entity("Wihngo.Models.Entities.PlatformWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("DerivationPath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("derivation_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("network");

                    b.Property<string>("PrivateKeyEncrypted")
                        .HasColumnType("text")
                        .HasColumnName("private_key_encrypted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Currency", "Network", "Address")
                        .IsUnique();

                    b.ToTable("platform_wallets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("549b7eb3-329e-4c25-8a0f-1774b3bad08b"),
                            Address = "TGRzhw2kwBW5PzncWfKCnqsvkrBezfsgiA",
                            CreatedAt = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2328),
                            Currency = "USDT",
                            IsActive = true,
                            Network = "tron",
                            UpdatedAt = new DateTime(2025, 12, 10, 0, 53, 14, 206, DateTimeKind.Utc).AddTicks(2329)
                        });
                });

            modelBuilder.Entity("Wihngo.Models.Love", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "BirdId");

                    b.HasIndex("BirdId");

                    b.ToTable("loves", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Story", b =>
                {
                    b.Property<Guid>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("story_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("HighlightOrder")
                        .HasColumnType("integer")
                        .HasColumnName("highlight_order");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsHighlighted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_highlighted");

                    b.HasKey("StoryId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BirdId");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.SupportTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<Guid>("SupporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("supporter_id");

                    b.HasKey("TransactionId");

                    b.HasIndex("BirdId");

                    b.HasIndex("SupporterId");

                    b.ToTable("support_transactions", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.SupportUsage", b =>
                {
                    b.Property<Guid>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("usage_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<Guid>("BirdId")
                        .HasColumnType("uuid")
                        .HasColumnName("bird_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.HasKey("UsageId");

                    b.HasIndex("BirdId");

                    b.HasIndex("ReportedBy");

                    b.ToTable("support_usage", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("profile_image");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.HasOne("Wihngo.Models.User", "Owner")
                        .WithMany("Birds")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Wihngo.Models.BirdPremiumSubscription", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany()
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Wihngo.Models.Entities.CryptoTransaction", b =>
                {
                    b.HasOne("Wihngo.Models.Entities.CryptoPaymentRequest", "PaymentRequest")
                        .WithMany()
                        .HasForeignKey("PaymentRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRequest");
                });

            modelBuilder.Entity("Wihngo.Models.Love", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("Loves")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "User")
                        .WithMany("Loves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wihngo.Models.Story", b =>
                {
                    b.HasOne("Wihngo.Models.User", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("Stories")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("Wihngo.Models.SupportTransaction", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("SupportTransactions")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "Supporter")
                        .WithMany("SupportTransactions")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Supporter");
                });

            modelBuilder.Entity("Wihngo.Models.SupportUsage", b =>
                {
                    b.HasOne("Wihngo.Models.Bird", "Bird")
                        .WithMany("SupportUsages")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wihngo.Models.User", "Reporter")
                        .WithMany("ReportedSupportUsage")
                        .HasForeignKey("ReportedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("Wihngo.Models.Bird", b =>
                {
                    b.Navigation("Loves");

                    b.Navigation("Stories");

                    b.Navigation("SupportTransactions");

                    b.Navigation("SupportUsages");
                });

            modelBuilder.Entity("Wihngo.Models.User", b =>
                {
                    b.Navigation("Birds");

                    b.Navigation("Loves");

                    b.Navigation("ReportedSupportUsage");

                    b.Navigation("Stories");

                    b.Navigation("SupportTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
